# Rust-only Dockerfile
FROM node:14-alpine

WORKDIR /usr/src/app
COPY . .

# Get Ubuntu packages
RUN apk update
RUN apk upgrade
RUN apk add bash
RUN apk add curl
RUN apk add build-base

# Get Rust
RUN curl https://sh.rustup.rs -sSf | bash -s -- -y

# Add cargo to path
ENV PATH="/root/.cargo/bin:${PATH}"

# Install stable Rust
RUN rustup install stable

# Set default toolchain
RUN rustup default stable

# Build the app
RUN yarn
RUN yarn build

CMD ["node", "build/app.js"]