name: Pull Request Tests

on:
  pull_request:
    branches:
      - main

env:
  CI: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build base image
        run: yarn docker:base:build

      - name: Build application image
        run: yarn docker:build

      - name: Run build and tests
        run: yarn docker:test
